# -*- coding: utf-8 -*-
"""week3_code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11s11aGej7Umw7SF498ZTFldILlQWu17Y
"""

# Data Visualization Dashboard
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset (built-in dataset for easy use)
df = sns.load_dataset('iris')

# Show basic info
print("Dataset Preview:")
print(df.head())

print("\nDataset Description:")
print(df.describe())
# 1. Scatter Plot (Relationship)
plt.figure()
sns.scatterplot(data=df, x='sepal_length', y='petal_length', hue='species')
plt.title("Sepal Length vs Petal Length")
plt.show()
# 2. Histogram (Distribution)
plt.figure()
sns.histplot(df['sepal_length'], kde=True)
plt.title("Distribution of Sepal Length")
plt.show()
# 3. Pairplot (All Relationships)
sns.pairplot(df, hue='species')
plt.show()
# 4. Heatmap (Correlation)
plt.figure()
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True)
plt.title("Feature Correlation Heatmap")
plt.show()